### ISSUE TITLE
mysqldump with generated column doesn't work while importing

### ISSUE THREAD

**Issue by karthikeayan** [databacker/mysql-backup#105]
I am getting below error when importing mysqldump taken from this docker image.

`ERROR 3105 (HY000) at line 82: The value specified for generated column 'column_name' in table 'table_name' is not allowed.`

Source and destination mysql server having same version.

MySQL server version:

`mysqld Ver 5.7.26 for Linux on x86_64 (MySQL Community Server (GPL))`

MySQL Dump client version:

`mysqldump Ver 10.17 Distrib 10.3.12-MariaDB, for Linux (x86_64)`

**Comment by deitch** [comment]
@karthikeayan can you run the dump manually off the database and see?

Also, if you run the `mysql-backup` image with debug enabled - `DB_DUMP_DEBUG=true` - you should see the mysqldump line. If it is possible to pull that line, post it here (omitting credentials, of course), and then see if we can replicate it? It is likely a version mismatch or some `mysqldump` bug, but let's figure it out and get it fixed either way.

Also, can you paste the relevant part of the dump output, based on the above, line 82 and its surrounding areas? Again, masking any sensitive info.

**Comment by karthikeayan** [comment]
I am not sure if this is fixable as this seems an mismatch between mysql and mariadb json functions. Your dockerfile uses alpine and alpine by default install mariadb client not mysql client.

More info: [https://dba.stackexchange.com/questions/240880/can-we-use-mariadb-mysqldump-cli-to-take-dump-from-mysql-community-version](https://dba.stackexchange.com/questions/240880/can-we-use-mariadb-mysqldump-cli-to-take-dump-from-mysql-community-version)

I also tried changing the base image to ubuntu in your Dockerfile to take dump. It works with 30MB database but when I use my image on 30GB database, mysqldump was very very slow and after creating 5-6GB of sql file the container got killed.

**Comment by deitch** [comment]
> mismatch between mysql and mariadb json functions

And so it appears. I would be tempted to ask the MariaDB team to fix it (they are pretty good about it), but this just may be a divergence. We may need to have separate mysql and mariadb images then.

> It works with 30MB database but when I use my image on 30GB database, mysqldump was very very slow and after creating 5-6GB of sql file the container got killed.

If you can replicate it without using your own sensitive data, can you open a new issue and put in exact steps to replicate?

**Comment by deitch** [comment]
> mismatch between mysql and mariadb json functions

I am curious as to why this hasn't been an issue until now. Do only certain scenarios trigger it? If you look at your dump file, what is it that triggered the problem?

**Comment by deitch** [comment]
Important reference point: https://elephantdolphin.blogspot.com/2018/11/a-tale-of-two-json-implementations.html

**Comment by karthikeayan** [comment]
I am just posting the first few characters from the line 82, as the complete line is too huge.

dump taken with mariadb client:

INSERT INTO \`feeds\` VALUES (1,1,2,'2017-05-30 10:28:54.944','{\"id\": 91, \"type\": \"Chart\", \"blocks\": [], \"options\": {\"chart\": {\"polar\": false, \"inverted\": false, \"zoomType\": \"x\"}, \"title\": {\"text\": \"Region ARPD\"}, \"xAxis\": {\"type\": \"category\",

dump taken with mysql client:
INSERT INTO \`feeds\` (\`ID\`, \`TENANT_ID\`, \`SHARED_BY\`, \`SHARED_ON_DATE\`, \`OPTIONS\`, \`DESCRIPTION\`, \`TITLE\`, \`UPDATED_ON\`, \`TOTAL_COUNT\`, \`ISHIDE\`, \`platform\`, \`isdeleted\`, \`UPDATED_BY\`) VALUES (1,1,2,'2017-05-30 10:28:54.944','{\"id\": 91, \"type\": \"Chart\", \"blocks\": [], \"options\": {\"chart\": {\"polar\": false, \"inverted\": false, \"zoomType\": \"x\"}, \"title\": {\"text\": \"Region ARPD\"}, \"xAxis\": {\"type\": \"category\", \"visible\": false, \"crosshair\": true, \"categories\": [\"Feb 01, 2017 To Mar 31, 2017\"]}, \"yAxis\": {\"min\": 0, \"title\": {\"text\": \"\"}, \"visible\": false}

**Comment by deitch** [comment]
Can you put it in a gist or somewhere we can see it?

**Comment by karthikeayan** [comment]
Created PR

**Comment by prvucetic** [comment]
Hey, what's the status of this? I'm facing this issue when try to restore to the same db server I created backup from. 

I have the following:

`/# mysql --version
mysql  Ver 8.0.21 for Linux on x86_64 (MySQL Community Server - GPL)`

`/# mysqldump --version
mysqldump  Ver 8.0.21 for Linux on x86_64 (MySQL Community Server - GPL)`

Tnx

**Comment by deitch** [comment]
There is a PR open, linked in this issue, needs to be rebased and cleaned.

**Comment by ToshY** [comment]
@deitch The only thing really needed is to replace `mariadb-client` in favor for `mysql-client`.

**Comment by deitch** [comment]
What happens with the go-based one? You can download the actual binary from [GitHub releases page](https://github.com/databacker/mysql-backup/releases/tag/v1.0.0-rc1), or run the docker image with the `1.0.0-rc1` tag. Be aware that the env vars have been revamped.

**Comment by dabico** [comment]
Unfortunately, I'm still facing the same issue. I tested this out with `databack/mysql-backup:latest`. Here's the compose file I used:

```yaml
version: '3.9'

services:

  test-database:
    image: mysql:8.2.0
    container_name: test-database
    restart: "always"
    volumes:
      - data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: test
      MYSQL_USER: testadmin
      MYSQL_PASSWORD: L33Th4Xx0r
      TZ: UTC
    healthcheck:
      test: mysqladmin ping -h localhost
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  test-backup:
    image: databack/mysql-backup:latest
    container_name: test-backup
    restart: "no"
    volumes:
      - backup:/backup
      - ./bkpdb/pre:/scripts.d/pre-backup
      - ./bkpdb/post:/scripts.d/post-backup
    environment:
      TZ: UTC
      DEBUG: true
      SAFECHARS: true
      DB_NAMES: test
      DB_PORT: 3306
      DB_USER: testadmin
      DB_PASS: L33Th4Xx0r
      DB_SERVER: test-database
      DB_DUMP_TARGET: /backup
      DB_DUMP_BEGIN: "0"
      RUN_ONCE: true
    depends_on:
      gse-database:
        condition: service_healthy

volumes:
  data:
    name: test-data
  backup:
    name: test-data-backups
```
