### ISSUE TITLE
 Got error: 2002: "Can't connect to MySQL server on 'db' (115)" when trying to connect

### ISSUE THREAD

**Issue by gremo** [databacker/mysql-backup#126]
My `docker-composer.yml` holds `db`, `mysql-backup` and `myadmin` services. Service `myadmin` can connect to `db` successfully. However, when `mysql-backup` starts, it can't connect. Inspecting the log:

>  Got error: 2002: "Can't connect to MySQL server on 'db' (115)" when trying to connect

Here is my `docker-compose.yml` file... any clue? Thanks

```yml
version: '3.7'

services:
    db:
        image: 'mariadb:10.4'
        ports:
            - '3307:3306'
        volumes:
            - 'db-data:/var/lib/mysql'
            - './config/db:/etc/mysql/conf.d:ro'
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    myadmin:
        image: 'phpmyadmin/phpmyadmin'
        ports:
            - '33078:80'
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    mysql-backup:
        image: 'databack/mysql-backup'
        depends_on:
            - db
        volumes:
            - './dumps:/db'
        environment:
            DB_SERVER: db
            DB_USER: root
            DB_PASS: ${MYSQL_ROOT_PASSWORD}
            DB_DUMP_TARGET: /db
            RUN_ONCE: 1

volumes:
    db-data:
```
