### ISSUE TITLE
Minio S3 Storage

### ISSUE THREAD

**Issue by kmplngj** [databacker/mysql-backup#128]
Hello,

I have a self hosted MiniO S3 Storage I like to use. Here is my docker compose:

```  
  backup:
    image: databack/mysql-backup
    restart: always
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /db-backups:/db
    #  - /path/to/pre-backup/scripts:/scripts.d/pre-backup
    #  - /path/to/post-backup/scripts:/scripts.d/post-backup
    environment:
     - DB_USER=root
     - DB_PASS=${DB_ROOT_PASSWORD}
     - DB_DUMP_FREQ=60
     - DB_DUMP_BEGIN=+1
     - DB_SERVER=mysql_db
     - DB_DUMP_TARGET=s3://enterprise/backup
     - AWS_ACCESS_KEY_ID=minio
     - AWS_SECRET_ACCESS_KEY=XYZZYX
     - AWS_DEFAULT_REGION=objectstorage
     - AWS_ENDPOINT_URL=https://objectstorage.XYZ.com/
```

```
backup_1      | upload failed: tmp/backups/db_backup_20200311092046.tgz to s3://enterprise/backup/db_backup_20200311092046.tgz Could not connect to the endpoint URL: "https://s3.eu-ms-vm1.amazonaws.com/enterprise/backup/db_backup_20200311092046.tgz"
```

When I run it mysql-backups tries to upload to Amazon AWS and not my defined. Is my config wrong?

Thanks for the help.
