### ISSUE TITLE
Saving multiple copies to AWS S3

### ISSUE THREAD

**Issue by rewieer** [databacker/mysql-backup#146]
Hello !
I'm using mysql-backup with the default config on my server :

```
  db_backup:
    depends_on:
      - db
    image: databack/mysql-backup
    restart: always
    environment:
      - DB_USER=${API_DB_NAME}
      - DB_PASS=${API_DB_PASSWORD}
      - DB_SERVER=db
      - DB_DUMP_TARGET=${AWS_DB_BUCKET}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
    networks:
      - backend
```

From the logs I can see it's dumping and uploading once a day
```
DB_PORT not provided, defaulting to 3306
Starting at Sat Oct 17 15:13:40 UTC 2020
./
./backup_2020-10-17T15:13:40Z.sql
upload: tmp/backups/db_backup_2020-10-17T15:13:40Z.tgz to s3://northwanderers/wanderers/backup/db/db_backup_2020-10-17T15:13:40Z.tgz
./
./backup_2020-10-18T15:13:40Z.sql
upload: tmp/backups/db_backup_2020-10-18T15:13:40Z.tgz to s3://northwanderers/wanderers/backup/db/db_backup_2020-10-18T15:13:40Z.tgz
./
./backup_2020-10-19T15:13:40Z.sql
upload: tmp/backups/db_backup_2020-10-19T15:13:40Z.tgz to s3://northwanderers/wanderers/backup/db/db_backup_2020-10-19T15:13:40Z.tgz
./
./backup_2020-10-20T15:13:40Z.sql
upload: tmp/backups/db_backup_2020-10-20T15:13:40Z.tgz to s3://northwanderers/wanderers/backup/db/db_backup_2020-10-20T15:13:40Z.tgz
./
./backup_2020-10-21T15:13:40Z.sql
upload: tmp/backups/db_backup_2020-10-21T15:13:40Z.tgz to s3://northwanderers/wanderers/backup/db/db_backup_2020-10-21T15:13:40Z.tgz
./
./backup_2020-10-22T15:13:40Z.sql
upload: tmp/backups/db_backup_2020-10-22T15:13:40Z.tgz to s3://northwanderers/wanderers/backup/db/db_backup_2020-10-22T15:13:40Z.tgz
./
./backup_2020-10-23T15:13:40Z.sql
upload: tmp/backups/db_backup_2020-10-23T15:13:40Z.tgz to s3://northwanderers/wanderers/backup/db/db_backup_2020-10-23T15:13:40Z.tgz
./
./backup_2020-10-24T15:13:40Z.sql
upload: tmp/backups/db_backup_2020-10-24T15:13:40Z.tgz to s3://northwanderers/wanderers/backup/db/db_backup_2020-10-24T15:13:40Z.tgz
./
./backup_2020-10-25T15:13:40Z.sql
upload: tmp/backups/db_backup_2020-10-25T15:13:40Z.tgz to s3://northwanderers/wanderers/backup/db/db_backup_2020-10-25T15:13:40Z.tgz
```

But when i go to the S3 panel, I see multiple, hundreds of my backup files, often spaced by exactly 2 minutes.
I might have a good hundred of files corresponding to the backup of 25/10/2020. I don't think my database is split in multiple files since it's really small (15M).
