### ISSUE TITLE
"Error: Invalid argument type" when 2 types added to DB_DUMP_TARGET

### ISSUE THREAD

**Issue by egahmad** [databacker/mysql-backup#156]
I followed the instructions added whitespace between local and s3 destination but I get a wrong type error, here's my docker-compose

```yaml
backup:
    image: databack/mysql-backup
    container_name: databack-backup
    restart: always
    volumes:
      - /db:/db
      - type: volume
        source: databack-pre
        target: /scripts.d/pre-backup
      - type: volume
        source: databack-post
        target: /scripts.d/post-backup
    environment:
      - DB_SERVER=mysql
      - DB_USER=user
      - DB_PASS=pass
      - DB_PORT=3306
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=2330
      - DB_DUMP_TARGET=/db s3://dir/db
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
    networks:
      - "db"
```
