### ISSUE TITLE
Can't connect to minio endpoint

### ISSUE THREAD

**Issue by ultrasites** [databacker/mysql-backup#158]
Hello,

i have an issue with mysql-backup. I want to connect it to minio on localhost:9500. It's a minio docker container with port forwarding 9500:9000. The bucket "haarwunder" is created.

The debug of mysql-backup says:
`upload failed: tmp/backups/db_backup_2021-04-11T12:04:34Z.tgz to s3://haarwunder/db_backup_2021-04-11T12:04:34Z.tgz Could not connect to the endpoint URL: "http://localhost:9500/haarwunder/db_backup_2021-04-11T12%3A04%3A34Z.tgz"`

Here is my docker-compose of mysql-backup:

```
haarwunder_db_backup:
    image: databack/mysql-backup:latest
    restart: always
    container_name: haarwunder_db_backup
    user: "0"
    networks:
      - haarwunder
    depends_on:
      - haarwunder_db
    environment:
      - DB_DUMP_FREQ=60
      - DB_DUMP_TARGET=/db
      - DB_SERVER=haarwunder_db
      - DB_USER=haarwunder
      - DB_PASS=haarwunder
      - DB_NAMES=haarwunder
      - DB_DUMP_DEBUG=true
      - AWS_ACCESS_KEY_ID=haarwunder
      - AWS_SECRET_ACCESS_KEY=haarwunder
      - AWS_ENDPOINT_URL=http://localhost:9500/
      - AWS_DEFAULT_REGION=us-east-1
      - DB_DUMP_TARGET=s3://haarwunder
    volumes:
      - ./backups:/db
```
      
      
Can anyone help me?

Thx.

**Comment by deitch** [comment]
My first suspicion is that you have networking issue. You hay have minio running on the host, with port-forwarding, but that only makes sure that minio can receive connections on port 9500 in:

* the host itself
* the minio container

You are trying to connect to `localhost:9500` from within the backup image, which means on its own.

This is not so much a backup issue, as a docker networking issue.

The general way to do this is either to pass the host's IP (which is not necessarily consistent) or to put both in the same compose yaml, which will ensure they have the same network, and then give it the endpoint of the container, e.g. 

```yaml
haarwunder_db_backup:
    image: databack/mysql-backup:latest
    restart: always
    container_name: haarwunder_db_backup
    user: "0"
    networks:
      - haarwunder
    depends_on:
      - haarwunder_db
    environment:
      - DB_DUMP_FREQ=60
      - DB_DUMP_TARGET=/db
      - DB_SERVER=haarwunder_db
      - DB_USER=haarwunder
      - DB_PASS=haarwunder
      - DB_NAMES=haarwunder
      - DB_DUMP_DEBUG=true
      - AWS_ACCESS_KEY_ID=haarwunder
      - AWS_SECRET_ACCESS_KEY=haarwunder
      - AWS_ENDPOINT_URL=http://minio:9500/
      - AWS_DEFAULT_REGION=us-east-1
      - DB_DUMP_TARGET=s3://haarwunder
    volumes:
      - ./backups:/db
minio:
  image: whatever
  # fill in lots more
```
