### ISSUE TITLE
Setting CRON expression raises exceptions in functions.sh

### ISSUE THREAD

**Issue by briosheje** [databacker/mysql-backup#160]
Setting a compose service like such:

```
mysql-backup:
    image: databack/mysql-backup
    depends_on:
      - mysql
    environment:
      - DB_DUMP_CRON=0 */4 * * *
      - DB_SERVER=mysql
      - DB_USER=${DB_USERNAME}
      - DB_PASS=${DB_PASSWORD}
      - DB_DUMP_TARGET=/db
      - DB_NAMES=dbname
      - MYSQLDUMP_OPTS=--no-tablespaces
    volumes:
      - ./mysql-data-backup:/db
    networks:
      - some-network
    restart: always
```

Raises the following exception every second:

```
BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.


Usage: seq [-w] [-s SEP] [FIRST [INC]] LAST


Print numbers from FIRST to LAST, in steps of INC.

FIRST, INC default to 1.


-w Pad to last with leading zeros

-s SEP String separator

/functions.sh: line 314: [: : integer expression expected

date: invalid date '2021.10.26-:0:00'

sleep: invalid number '-1635234660'

./

./backup_2021-10-26T07:51:53Z.sql
```

A tgz file is created every second instead of every 4 hours

`/functions.sh: line 314: [: : integer expression expected` seems to be the root cause of the problem, am I missing something?
