### ISSUE TITLE
question: how to trigger manually a backup when container is alrady running with DB_DUMP_BEGIN ?

### ISSUE THREAD

**Issue by michabbb** [databacker/mysql-backup#163]
hi,

i wasn´t able to find the answer here, so I have to ask.
if the container is already running, how do I trigger "only once" a backup with "docker exec ...." ??

thanks!

**Comment by deitch** [comment]
I cannot think of the way off the top of my head. Why not just start a new container with run-once?

**Comment by michabbb** [comment]
because (in my 👀 ) it´s better to use an existing running container as starting things multiple times.
secondly, I need two different configs/setups, one for "run as cron" and one for "run once" which
is an overhead. if something changes, I have to modify two calls. this is not the end of the world,
I was just asking in case there is a preferred way for this special need.

thanks!

**Comment by Glideh** [comment]
Thanks for this great tool @deitch.
For me, the issue is when you are using `docker-compose` with all your config there, like:

```yml
#...
  backup:
    image: databack/mysql-backup:ee17125b37e354e34d322a0ccbf61e144d542a0f
    restart: unless-stopped
    volumes:
      - ./backup:/db
    user: "0"
    depends_on:
      - db
    environment:
      DB_DUMP_TARGET: /db
      DB_SERVER: db
      DB_DUMP_FREQ: "1440"
      DB_DUMP_BEGIN: "0500"
      DB_NAMES: my_db
      DB_USER: my_user
      DB_PASS: my_pass
```

I though we could do something like that in order to **avoid typing the same whole config in a command**

```
docker-compose exec backup /run_backup.sh
```

Then I though we could at least override the `RUN_ONCE` var with

```
docker-compose run --rm -e RUN_ONCE=1
```

But this doesn't seem to work either, at least it's not doing anything until it receives a `SIGINT` where it creates the backup then keeps active until a next `SIGINT` and so on (needs to be `docker stop`ped).
