### ISSUE TITLE
no support for docker-compose ?

### ISSUE THREAD

**Issue by vulkanosaure** [databacker/mysql-backup#164]
Hello,

I was trying to setup your image in a docker compose setup doing the following 

```
db_backup2:
    image: databack/mysql-backup
    restart: always
    depends_on:
      - db
    volumes:
      - db_backup:/var/backup
    environment:
      - DB_USER: ${DB_USER}
      - DB_SERVER: dbserver
      - DB_PORT: 1111
      - DB_PASS: ${DB_PWD}
      - DB_NAMES: my_db
      - DB_DUMP_FREQ: 1
      - DB_DUMP_BEGIN: 0100
      - DB_DUMP_DEBUG: true
      - DB_DUMP_TARGET: /var/backup
```

but when trying to run it, i get the error

> services.db_backup2.environment contains {"DB_USER": "test"}, which is an invalid type, it should be a string

Is this not meant to be used in a docker-compose setup ?
I'm new to Docker, and I'd really like to have my db backup part of my whole dockerized stack, 
or would that be considered bad practice for some reason ?
