### ISSUE TITLE
docker-compose setup not working

### ISSUE THREAD

**Issue by dassoop** [databacker/mysql-backup#166]
I am trying to setup backup in my docker-compose but am getting this error. Any help would be appreciated!

`ERROR: pull access denied for mysql-backup, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

```
mysql-backup:
    image: mysql-backup:1
    environment:
      DB_SERVER: mysql-db
      DB_USER: root
      DB_PASS: root
      DB_DUMP_TARGET: s3://bucketname/_mysql-backup/
      DB_DUMP_FREQ: 1
      AWS_ACCESS_KEY_ID: keykeykeykeykeykeykeykeykeykeykeykeykeykey
      AWS_SECRET_ACCESS_KEY: keykeykeykeykeykeykeykeykeykeykeykeykeykey
      COMPRESSION: bzip2
    volumes:
      - /var/lib/mysql:/var/lib/mysql:ro
```
