### ISSUE TITLE
proper docker-compose setup

### ISSUE THREAD

**Issue by dassoop** [databacker/mysql-backup#167]
I am getting these errors when starting the container: 

```
runtime-errors:
mysql-backup_1      | DB_PORT not provided, defaulting to 3306
mysql-backup_1      | Starting at Mon Nov 15 22:07:15 UTC 2021
mysql-backup_1      | mysqldump: Got error: 2002: "Can't connect to MySQL server on 'mysql-standalone' (115)" when trying to connect
mysql-backup_1      | rm: can't remove '/tmp/backups/db_backup_2021-11-15T22:07:15Z.tbz2': No such file or directory
```

Once it is started it seems to be working properly, every minute it throws this in the log. However in the /tmp/backups folder there is nothing and nothing is being uploaded to the bucket:

```
mysql-backup_1      | ./
mysql-backup_1      | ./backup_2021-11-15T22:14:15Z.sql
```

Here is the docker-compose file I am using. I am not sure where the DB_Server should be pointed. Should it be mysql-standalone/DatabaseName ? 

```
version: '3.0'
volumes:
  mysql-data:
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=DatabaseName
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  springboot:
    image: springboot-docker-container
    ports:
      - "80:8080"
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone/DatabaseName?serverTimezone=America/Los_Angeles
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: './'
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone

  mysql-backup:
    image: databack/mysql-backup
    environment:
      DB_SERVER: mysql-standalone
      DB_USER: root
      DB_PASS: root
      DB_DUMP_FREQ: 1
      DB_DUMP_TARGET: https://s3://nameofthebucket/_mysql-backup/
      AWS_ACCESS_KEY_ID: key
      AWS_SECRET_ACCESS_KEY: key
      COMPRESSION: bzip2
    volumes:
      - /var/lib/mysql:/var/lib/mysql:ro

```
