### ISSUE TITLE
[Question] How to run without root?

### ISSUE THREAD

**Issue by cod3rshotout** [databacker/mysql-backup#186]
I already saw [this discussion ](https://github.com/databacker/mysql-backup/issues/60) and I read the permission section of the documentation and still I'm confused about this.

So I executed the container using `docker-compose`:

```
backup:
  container_name: bcm_backup
  restart: always
  image: databack/mysql-backup
  user: "0"
  depends_on:
    - database
  volumes:
    - /home/john/backup/app:/backup
  environment:
    - DB_USER=${DB_USER}
    - DB_SERVER=bcm_db
    - DB_PORT=${DB_PORT}
    - DB_PASS=${DB_PWD}
    - DB_NAMES=${DB_NAME}
    - DB_DUMP_FREQ=1
    - DB_DUMP_BEGIN=+0
    - DB_DUMP_DEBUG=true
    - DB_DUMP_TARGET=/backup
```
The code above works as expected but it creates the folder as root. My docker container is running as rootless, and I don't want that the generated file are owned by root. So I tried to set   `user: "1000"` which is the result of my user: `id -u john` but I get:

> Permission denied

I cannot chown the user `appuser` 'cause I doesn't want to create a new user on the system since I'm executing the container as rootless.

So the question is: is there a way to generate the backup as `john` user?

Thanks
