### ISSUE TITLE
Do we need volume if we are pushing to smb server?

### ISSUE THREAD

**Issue by git-avinash** [databacker/mysql-backup#200]
Error
```
Starting at Thu Jul 14 21:14:08 UTC 2022
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
./
./backup_2022-07-14T21:14:08Z.sql
directory_create_or_exist: lstat failed on directory /var/lib/samba/private/msg.sock: Permission denied
Unable to initialize messaging context
tree connect failed: NT_STATUS_BAD_NETWORK_NAME
```

Docker Compose Env:
```
environment:
      DB_SERVER: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASS: pass
      # DB_DUMP_KEEP_PERMISSIONS: false
      DB_DUMP_TARGET: smb://server-ip/my-bkp
      DB_DUMP_FREQ: 1440
      SMB_USER: smbusr
      SMB_PASS: smbpass
```
