### ISSUE TITLE
SMB backup issue

### ISSUE THREAD

**Issue by git-avinash** [databacker/mysql-backup#202]
```
./backup_2022-07-14T21:28:24Z.sql
directory_create_or_exist: lstat failed on directory /var/lib/samba/private/msg.sock: Permission denied
Unable to initialize messaging context
tree connect failed: NT_STATUS_BAD_NETWORK_NAME
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
./
./backup_2022-07-15T21:28:25Z.sql
directory_create_or_exist: lstat failed on directory /var/lib/samba/private/msg.sock: Permission denied
Unable to initialize messaging context
tree connect failed: NT_STATUS_BAD_NETWORK_NAME
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
./
```

If it's a mistake on my end then is this the right way to make an SMB backup?
```
db-backup:
    image: databack/mysql-backup
    restart: always
    networks:
      - my-net
    links:
      - db
    environment:
      DB_SERVER: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASS: pass
      # DB_DUMP_KEEP_PERMISSIONS: false
      DB_DUMP_TARGET: smb://ipp/storage
      DB_DUMP_FREQ: 1440
      SMB_USER: smbuser
      SMB_PASS: smbpass
```

**Comment by deitch** [comment]
This looks like a duplicate of #200 ; if so, please check the latest tagged version and use that, and close this issue.

```yaml
image: databack/mysql-backup
```

This uses the implicit tag of `latest`, which always is unstable (hence not a great idea). `mysql-backup` follows a common pattern where:

* `latest` => most recent semver release
* `master` => most recent update to master (mainline or trunk) branch

Both are mutable and provided as conveniences. You should use an explicit tag.

**Comment by git-avilabs** [comment]
understood but is my schema right? Is this how u write compose for backup on sbm?

**Comment by deitch** [comment]
Looks like it.

**Comment by git-avilabs** [comment]
results using `master` tag:
```
Starting at Fri Jul 29 08:45:48 UTC 2022
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
./
./backup_2022-07-29T08:45:48Z.sql
tree connect failed: NT_STATUS_BAD_NETWORK_NAME
```

**Comment by git-avilabs** [comment]
results using `latest` tag:

```
Starting at Fri Jul 29 08:48:54 UTC 2022
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
./
./backup_2022-07-29T08:48:54Z.sql
directory_create_or_exist: lstat failed on directory /var/lib/samba/private/msg.sock: Permission denied
Unable to initialize messaging context
tree connect failed: NT_STATUS_BAD_NETWORK_NAME
```

**Comment by git-avilabs** [comment]
I am able to access my smb storage using my mac so my samba is running properly

**Comment by git-avilabs** [comment]
results using `64da50c8e5196fd820a2eb5b75bd5b73456927de` tab:

```
Starting at Fri Jul 29 08:51:38 UTC 2022
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
./
./backup_2022-07-29T08:51:38Z.sql
tree connect failed: NT_STATUS_BAD_NETWORK_NAME
```

**Comment by git-avilabs** [comment]
@deitch can u please check my issue

**Comment by git-avilabs** [comment]
I tried to set backup to server itself to check if it works:

```
db-backup:
    image: databack/mysql-backup:master
    restart: always
    networks:
      - backend-net
    user: root
    links:
      - db
    environment:
      DB_SERVER: db
      DB_PORT: 3306
      DB_USER: linkedindb
      DB_PASS: 834fYS9EJ-h3KD75LN
      DB_DUMP_KEEP_PERMISSIONS: false
      DB_DUMP_TARGET: /db
      DB_DUMP_FREQ: 1440
    volumes:
     - /home:/db
```

and it still gives error

```
Starting at Sat Aug 6 05:19:36 UTC 2022
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
./
./backup_2022-08-06T05:19:36Z.sql
```

but! file was found on /home 
```
root@my-server:/home# ls
db_backup_2022-08-06T05:16:40Z.tgz  db_backup_2022-08-06T05:19:36Z.tgz
```
