### ISSUE TITLE
New schemas not backed up

### ISSUE THREAD

**Issue by bansalvinay** [databacker/mysql-backup#214]
I'm using Ubuntu Mysql image. 
The backup runs fine for the databases which are created before this container is started. It runs for these databases continuously on cron as expected. But when there are new databases created, these are not backed up until this container is restarted. 

Here's my composer code for mysql-backup : 

```
db-backup:
    image: databack/mysql-backup:latest
    restart: 'always'
    container_name: 'smartsites-db-backup'
    depends_on: 
      - database
    volumes:
      - ${DB_BACKUP_DIR}:/db
      - ${DB_BACKUP_TEMP_DIR}:/tmp
    user: root
    environment:
      DB_SERVER: database
      DB_PORT: 3306
      DB_USER: root
      COMPRESSION: gzip
      DB_DUMP_BY_SCHEMA: "true"
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      DB_DUMP_CRON: "* * * * *"
      DB_DUMP_DEBUG: "true"
      DB_DUMP_TARGET: /db
```
