### ISSUE TITLE
Adding RESTORE_OPTS env parameter for restore

### ISSUE THREAD

**Issue by scicco** [databacker/mysql-backup#225]
Hello,

I'm currently using this image to backup an SSL-protected Mysql specifying an env file inside docker-compose.yml 

The env file has several options like this:

```
...
MYSQLDUMP_OPTS="--ssl-cert /certs/client-cert.pem --ssl-key /certs/client-key.pem"
...
```

This is the docker-compose.yml relevant part:

``` 
...
  mysql_db_backup:
    image: databack/mysql-backup
    env_file: $HOME/myproject/mysql_db/env
    environment:
      - DB_DUMP_CRON="0 3 * * *"
    user: "0"
    restart: always
    volumes:
      - type: bind
        source: $HOME/myproject/mysql_db/backup
        target: /backup
      - $HOME/myproject/mysql_db/target.sh:/scripts.d/target.sh
      - $HOME/myproject/mysql_db/data/client-cert.pem:/certs/client-cert.pem:ro
      - $HOME/myproject/mysql_db/data/client-key.pem:/certs/client-key.pem:ro
    depends_on:
      mysql_db:
        condition: service_healthy
...
```

I'm using this image also for disaster recovery to perform a restore of the latest backup. Currently, there is no support for providing any option to the restore, so I'm not able to restore an SSL-protected database

Could you please consider adding **RESTORE_OPTS** env parameter, passing these options in the restore command invocation so that I can add this line inside my env file:

```
...
RESTORE_OPTS="--ssl-cert /certs/client-cert.pem --ssl-key /certs/client-key.pem"
...
```

and perform restore successfully?

Thank you in advance
