### ISSUE TITLE
[Bug] Entrypoint error: exec /entrypoint: exec format error

### ISSUE THREAD

**Issue by GuillermoFarias** [databacker/mysql-backup#229]
introduced a bug inside entrypoint in this PR https://github.com/databacker/mysql-backup/pull/228

I get this error when executing: 
```sh
exec /entrypoint: exec format error
```

```yml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
  namespace: app
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: DB_DUMP_TARGET
              value: s3://mybucket
            - name: AWS_ACCESS_KEY_ID
              value: myawskeyid
            - name: AWS_SECRET_ACCESS_KEY
              value: myawssecretkey
            - name: AWS_DEFAULT_REGION
              value: myawsregion
            - name: DB_SERVER
              value: mydbserver
            - name: DB_PORT
              value: mydbport
            - name: DB_USER
              value: mydbuser
            - name: DB_PASS
              value: mydbpass
            - name: RUN_ONCE
              value: "true"
            image: databack/mysql-backup
            imagePullPolicy: Always
            name: mysql-backup-s3
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
  schedule: 0 */6 * * *
  suspend: false
```
With version v0.12.0 this does not happen and everything is ok
