### ISSUE TITLE
cat: '/tmp/restore.1/*': No such file or directory

### ISSUE THREAD

**Issue by AxelGuignard** [databacker/mysql-backup#235]
When restoring a backup, I get the message "cat: '/tmp/restore.1/*': No such file or directory".

Here is my docker-compose config:
```
mysql-restore:
    image: databack/mysql-backup
    volumes:
      - "./db:/db"
    networks:
      - backend
    environment:
      - DB_SERVER=mysql
      - DB_USER=${DB_BACKUP_USER}
      - DB_PASS=${DB_BACKUP_PASSWORD}
      - DB_RESTORE_TARGET=/db/daily/backup_D_2023-09-07.gz
      - RUN_ONCE=true
```
(The target is temporary set with a fixed value, it should be a variable)

Here is a fragment of the result of the command `docker compose run -e DB_DUMP_DEBUG=true mysql-restore` that seems to be the cause of the error:
```
+ workdir=/tmp/restore.1
+ rm -rf /tmp/restore.1
+ mkdir -p /tmp/restore.1
+ gunzip
+ tar -C /tmp/restore.1 -xvf -
./
+ cat '/tmp/restore.1/*'
+ mysql -h mysql -P 3306 -uuser '-p#########'
cat: '/tmp/restore.1/*': No such file or directory
+ rm -rf /tmp/restore.1
+ /bin/rm -f /tmp/restorefile
+ '[' -d /scripts.d/post-restore/ ']'
```
