### ISSUE TITLE
Unknown flag: --config-file

### ISSUE THREAD

**Issue by sgpublic** [databacker/mysql-backup#243]
First of all, thank you for your great work on mysql-backup, but I have some questions.

I deployed mysql-backup using docker-compose according to the [description](https://github.com/databacker/mysql-backup#backup) in the readme:

```yaml
version: "3"
services:
  mysql-backup:
    image: databack/mysql-backup:1.0.0-rc1
    user: 1000:1000
    volumes:
      - /mnt/drive/OneDrive/Backups/MariaDB:/data
      - /mnt/core/var/tmp/mysql-backup:/var/tmp/mysql-backup
      - /mnt/drive/OneDrive/Backups/MySQL-Backup:/config
    networks:
      - mariadb-network
    restart: always
    entrypoint: ["/mysql-backup", "--config-file=/config/config.yaml"]

networks:
  mariadb-network:
    name: mariadb-network
```

And my config file:

```yaml
database:
  server: mariadb
  port: 3306
  credentials:
    username: user
    password: xxxx
dump:
  targets: /data
  scripts:
    post-backup: /config/post-backup
tmp: /var/tmp/mysql-backup
logging: debug
```

But I got these error logs:

```
time="2023-11-20T07:06:44Z" level=fatal msg="unknown flag: --config-file"
```

So how should I configure it to use 1.0.0-rc1? Thank you!
