### ISSUE TITLE
mysqldump: Couldn't execute 'SHOW FIELDS FROM `host_summary`':

### ISSUE THREAD

**Issue by fernandovs4** [databacker/mysql-backup#276]
Hello! Pleasure! Can i help me? 
i have its docker-compose
services:
  db-mysql-5.7.21:

    image: mysql:5.7.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mypassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /volume1/docker_compose/db_mysql_5.7.21_una/appdir/config:/etc/mysql/conf.d
      - /volume1/docker_compose/db_mysql_5.7.21_una/appdir/data:/var/lib/mysql
    networks:
      - myNetwork

  backup:
    image: databack/mysql-backup
    restart: always
    volumes:
      - /volume1/docker_compose/db_mysql_5.7.21_una/db_dumps2:/db
    environment:   # Usando a chave correta 'environment' para definir variáveis de ambiente
      - DB_DUMP_TARGET=/db
      - DB_USER=myuser
      - DB_PASS=mypass
      - DB_DUMP_FREQ=1
      - DB_SERVER=db-mysql-5.7.21
    depends_on:
      - db-mysql-5.7.21
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge

but i find this error in databack/mysql-backup 
mysqldump: Couldn't execute 'SHOW FIELDS FROM `host_summary`': View 'sys.host_summary' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them (1356)
cp: cannot stat '/tmp/backups/db_backup_2024-03-06T21:31:14Z.tgz': No such file or directory
rm: cannot remove '/tmp/backups/db_backup_2024-03-06T21:31:14Z.tgz': No such file or directory

**Comment by deitch** [comment]
Looks like you are running the legacy bash-based version. Can you enable debug logging and post here? Just be sure to filter out any sensitive information.

```yaml
  backup:
    image: databack/mysql-backup
    restart: always
    volumes:
      - /volume1/docker_compose/db_mysql_5.7.21_una/db_dumps2:/db
    environment:   # Usando a chave correta 'environment' para definir variáveis de ambiente
      - DB_DUMP_TARGET=/db
      - DB_USER=myuser
      - DB_PASS=mypass
      - DB_DUMP_FREQ=1
      - DB_SERVER=db-mysql-5.7.21
      - DB_DUMP_DEBUG=true    # <--- THIS IS THE CHANGE
    depends_on:
      - db-mysql-5.7.21
    networks:
      - myNetwork

```
