### ISSUE TITLE
How to create a backup copy of not only data and tables, but also functions and procedures?

### ISSUE THREAD

**Issue by GMELUM** [databacker/mysql-backup#289]
```
  mysql-master-backup:
    image: databack/mysql-backup
    container_name: mysql-backup
    restart: always
    environment:
      SINGLE_DATABASE: true
      DB_SERVER: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: $MYSQL_PASSWORD
      DB_NAMES: $MYSQL_DATABASE
      DB_DUMP_FREQ: $INTERVAL
      DB_DUMP_TARGET:  "s3://$AWS_BUCKET/dumps/$MYSQL_DATABASE"
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_REGION: $AWS_REGION
      AWS_ENDPOINT_URL: $AWS_ENDPOINT
      COMPRESSION: bzip2
    command: dump
```
