### ISSUE TITLE
How to set DB_DUMP_FILENAME_PATTERN

### ISSUE THREAD

**Issue by maitrungduc1410** [databacker/mysql-backup#303]
I'm running this as docker container and trying to custom dump filename but it's not working no matter using env or command flag:

```yml
db_backup:
  image: databack/mysql-backup
  command: dump --filename-pattern=my_db_backup.tgz
  
db_backup:
  image: databack/mysql-backup
  environment:
    - DB_DUMP_FILENAME_PATTERN=my_db_backup.tgz
```
dump file name is always like this `db_backup_2024-04-26T15:56:28Z.tgz`

Please help, Thanks

**Comment by deitch** [comment]
Assuming that your config above is accurate, you are using the `latest` tag, which is the somewhat older script-based version (completely revamped is due GA as 1.0.0 really shortly). You can run it with debug via env var `DB_DUMP_DEBUG=true`. Then paste your output but _please_ check that you don't leak any secrets in the logs.

The newer version is much better about that.

**Comment by skywalkerisnull** [comment]
I have the same issue, this is my config

```yaml
  mysql-backup:
    image: databack/mysql-backup:1.0.0-rc5
    restart: always
    environment:
      DB_SERVER: db
      DB_USER: ********
      DB_PASS: ************
      DB_NAMES: ************
      DB_DUMP_TARGET: s3://backups-******
      DB_DUMP_BEGIN:
      DB_DUMP_FREQ: 360
      AWS_ACCESS_KEY_ID: ****
      AWS_SECRET_ACCESS_KEY: ******
      AWS_ENDPOINT_URL: https://s3.ap-southeast-2.amazonaws.com
      AWS_DEFAULT_REGION: ap-southeast-2
      AWS_REGION: ap-southeast-2
      COMPRESSION: gzip
      DB_DUMP_FILENAME_PATTERN: replica-{{.now}}.tgz
      DB_DUMP_DEBUG: true
      TZ: Australia/Sydney
      NICE: true
    command: dump
```

And the only log I get in console is:
`mysql-backup-1  | time="2024-08-15T23:21:07Z" level=info msg="beginning dump 2024-08-15T23:21:07Z" run=185f342c-6328-4c69-8071-f23b466a66c6`

I can see the tgz file appear in the S3 bucket with the filename of: `db_backup_2024-08-15T23:21:07Z.tgz`
