### ISSUE TITLE
Retention again :-(

### ISSUE THREAD

**Issue by sonor3000** [databacker/mysql-backup#311]
Sorry to come up again with this topic, but I am not able to get retention to work.

In my running container, I am using the :latest tag, the mysql-backup commandline looks like this if I list the running processes:

/mysql-backup dump --target /db --server mariadb --user root --pass secret --retention 2c --frequency 1

Every minute a backup is created but no old backups are deleted.

What am I doing wrong?

**Comment by deitch** [comment]
>  I am using the :latest tag

The tag `:latest`? That one does not support retention. It only was added in the 1.x series (which currently is release candidate).

**Comment by PaBox** [comment]
Even with the following docker configuration, it is not working:

```yaml
database-server:
    image: mariadb
    container_name: database-server
    command: [ "--max_connections=1024", "--verbose"]
    # tty: true
    # stdin_open: true
    user: 1599:1600
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: /run/secrets/secret_pw_root_mysql
      MYSQL_DATABASE: mc_db
      MYSQL_USER: mc
      MYSQL_PASSWORD: /run/secrets/secret_pw_user_mysql
    secrets:
      - secret_pw_root_mysql
      - secret_pw_user_mysql
    restart: on-failure:5
    volumes:
      - db-server-volume:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 0m
      interval: 10s
      retries: 25
    networks:
      - mc-backup-network
      - mc-proxy-network
  db-backup-server:
    image: databack/mysql-backup:1.0.0 # check appropriate image tags
    container_name: db-backup-server
    user: 1599:1600
    environment:
      TZ: Europe/Berlin
      DB_DUMP_DEBUG: true
      # DB_DUMP_SAFECHARS: true
      DB_SERVER: database-server
      DB_USER: mc
      DB_PASS: /run/secrets/secret_pw_user_mysql
      DB_DUMP_TARGET: /db
      DB_DUMP_BEGIN: "+0"
      DB_DUMP_FREQUENCY: 1
      RETENTION: "2c"
    command: dump
    secrets:
      - secret_pw_user_mysql
    restart: always
    depends_on:
      database-server:
        condition: service_healthy
    volumes:
      - db-backup-volume:/db
    networks:
      - mc-backup-network
```

So even with 1.0.0, the retention is not working correctly (in my case).

Also there are no errors to report, even with debug output enabled. Really weird. Shouldn't it be at least reporting an issue if retention != "" ?
