### ISSUE TITLE
Dump: bigint type issue

### ISSUE THREAD

**Issue by lightsuner** [databacker/mysql-backup#313]
## Versions
**MySQL**: 8.4
**databack/mysql-backup**: 738cc8f5f77947dc83ae8eb69228d27674fdd493

## Issue
I've just unpacked one of the recent backups and spotted the issue: for some reason, during a backup, it can not convert properly **bigint** type. Please check the example of the backup file:

```sql
--
-- Table structure for table `languages`
--

DROP TABLE IF EXISTS `languages`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `languages` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(2) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `languages_code_unique` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `languages`
--

LOCK TABLES `languages` WRITE;
/*!40000 ALTER TABLE `languages` DISABLE KEYS */;
INSERT INTO `languages` (`id`, `code`, `created_at`, `updated_at`) VALUES ('%!s(*uint64=0xc000598008)','en','2024-05-19 22:20:46','2024-05-19 22:20:46');
/*!40000 ALTER TABLE `languages` ENABLE KEYS */;
UNLOCK TABLES;
```

So, as you can see, instead of (I guess) ``1``, it dumped `%!s(*uint64=0xc000598008)`. It seems like a memory reference.

**Comment by deitch** [comment]
Nice catch. Can you write a simple way to recreate it? Give a simple sql file to load into a fresh DB, that causes it when dumped?

**Comment by lightsuner** [comment]
@deitch  will try

**Comment by lightsuner** [comment]
Hello @deitch , here is how to reproduce the bug:

You need to create 2 files:
* compose.yml
* init_db.sql

``compose.yml``
```yaml
version: '3.8'

networks:
  default:
    driver: bridge
    name: bug

services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3306:3306'
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - default
```

``init_db.sql``
```sql
CREATE DATABASE IF NOT EXISTS main CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

USE `main`;

CREATE TABLE `languages`
(
    `id`         bigint unsigned NOT NULL AUTO_INCREMENT,
    `code`       varchar(2) NOT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `languages_code_unique` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO `languages` (`code`, `created_at`, `updated_at`) VALUES ('en', NOW(), NOW());
INSERT INTO `languages` (`code`, `created_at`, `updated_at`) VALUES ('de', NOW(), NOW());
```

**Run docker compose**:

``docker compose up -d``

**And than run command**:

```sh
docker run --network=bug \
-v ${PWD}/backups:/backups \
-e DB_SERVER=mysql \
-e DB_USER='root' \
-e DB_PORT='3306' \
-e DB_NAMES='main' \
-e DB_PASS='root_password' \
-e DB_DUMP_TARGET='/backups' \
 databack/mysql-backup:738cc8f5f77947dc83ae8eb69228d27674fdd493 dump --once
```

After, check ``./backups`` folder


Thanks in advance!
