### ISSUE TITLE
Environment Variable "Debug" not producing debug logs

### ISSUE THREAD

**Issue by skywalkerisnull** [databacker/mysql-backup#341]
In my docker compose file, I have the following config, the `DEBUG: true` has no effect. Instead I have been passing an additional flag to the `command: dump -v=2` to get the debug/trace logs.

```yaml
  mysql-backup:
    image: databack/mysql-backup:1.0.0-rc5
    restart: always
    environment:
      DUMP: true
      DEBUG: true
      DB_SERVER: db
      DB_USER: ********
      DB_PASS: ************
      DB_NAMES: ************
      DB_DUMP_TARGET: s3://backups-******
      DB_DUMP_BEGIN:
      DB_DUMP_FREQ: 360
      AWS_ACCESS_KEY_ID: ****
      AWS_SECRET_ACCESS_KEY: ******
      AWS_ENDPOINT_URL: https://s3.ap-southeast-2.amazonaws.com
      AWS_DEFAULT_REGION: ap-southeast-2
      AWS_REGION: ap-southeast-2
      COMPRESSION: gzip
      DB_DUMP_FILENAME_PATTERN: replica-{{.now}}.tgz
      DB_DUMP_DEBUG: true
      TZ: Australia/Sydney
      NICE: true
    command: dump
```

https://github.com/databacker/mysql-backup/issues/303#issuecomment-2306910826
