### ISSUE TITLE
Docker Secrets no longer working

### ISSUE THREAD

**Issue by ShawnDordeJay** [databacker/mysql-backup#383]
Since updating to version 1.0.0, Docker Secrets no longer work for me. These settings worked before the update. I wasn’t sure if the password might be incorrect, so I commented out `DB_PASS_FILE` and added `DB_PASS=<my password>` instead. After that, the dump started successfully.

However, I’d prefer not to have the password in plain text in the Docker Compose file or in the .env file.

Here's my Docker Compose File:
```
secrets:
  mysql_password:
    file: $SECRETSDIR/mysql_password

services:
  mysqlbackup:
    container_name: mysqlbackup
    image: databack/mysql-backup:latest
    restart: always
    volumes:
      - $DOCKERDIR/mysqlbackup/data:/data
      - $DOCKERDIR/mysqlbackup/tmp:/tmp
    environment:
      - DB_PORT=<port>
      - DB_DUMP_TARGET=/data
      - TMP_PATH=/tmp
      - DB_USER=<user>
      - DB_PASS_FILE=/run/secrets/mysql_password
      - DB_DUMP_ONCE
      - DB_SERVER=<IP>
      - DB_DUMP_SAFECHARS=-
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - DB_DEBUG
    command: dump
    secrets:
      - mysql_password
```

Here's the log:

> time="[TIMESTAMP]" level=info msg="beginning dump [TIMESTAMP]" run=UUID
> Error: error running command: error running command: error running dump: failed to list database schemas: could not get schemas: dial tcp [IP]:[PORT]: connect: connection refused
> time="[TIMESTAMP]" level=fatal msg="error running command: error running command: error running dump: failed to list database schemas: could not get schemas: dial tcp [IP]:[PORT]: connect: connection refused"
> time="[TIMESTAMP]" level=info msg="beginning dump [TIMESTAMP]" run=UUID
> Error: error running command: error running command: error running dump: failed to list database schemas: could not get schemas: Error 1045 (28000): Access denied for user '[USER]'@'[HOST]' (using password: NO)
> time="[TIMESTAMP]" level=fatal msg="error running command: error running command: error running dump: failed to list database schemas: could not get schemas: Error 1045 (28000): Access denied for user '[USER]'@'[HOST]' (using password: NO)

Thank you very much for your help!
