### ISSUE TITLE
Permissions Issues with Creating Backup???

### ISSUE THREAD

**Issue by kevdogg** [databacker/mysql-backup#386]
I'm actually not sure what the error is attributable to.  Here is my error:

```
time="2024-12-03T17:38:00Z" level=debug msg="starting dump"
time="2024-12-03T17:38:00Z" level=info msg="beginning dump 2024-12-03T17:38:00Z" run=627211e8-32ba-4956-bcd3-a84685306ca0
time="2024-12-03T17:38:01Z" level=debug msg="uploading via protocol file from db_backup_2024-12-03T17:38:00Z.tgz to db_backup_2024-12-03T17:38:00Z.tgz" run=627211e8-32ba-4956-bcd3-a84685306ca0
Error: error running command: error running command: error running dump: failed to push file: open /tmp/databacker_backup1650887563/db_backup_2024-12-03T17:38:00Z.tgz: no such file or directory
```

Here is my compose file sections:

```
  mariadb:
    container_name: mariadb
    image: ghcr.io/linuxserver/mariadb:latest
    restart: always
    hostname: mariadb-bitwarden_rs
    secrets:
      - mysql-user_secret
      - mysql-root_secret
    networks:
      - bitwarden_rs_net
    ports:
      - 3306:3306
    healthcheck:
      <<: *mariadb-healthcheck
    environment:
      - TZ
      - PUID=0
      - GUID=0
      - MYSQL_DATABASE=bitwarden
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/mysql-root_secret
      - MYSQL_USER=bwuser
      - FILE__MYSQL_PASSWORD=/run/secrets/mysql-user_secret
      #- MYSQL_PASSWORD=bwuserpass
    volumes:
      - /var/data/db:/config
      - /etc/localtime:/etc/localtime:ro

  mariadb-backup:
    container_name: mariadb-backup
    image: databack/mysql-backup:latest
    restart: unless-stopped
    #user: root
    secrets:
      - mysql-root_secret
      - mysql-user_secret
    networks:
      - bitwarden_rs_net
    depends_on:
      <<: *mariadb-depends
    command: dump
    environment:
      - TZ
      - DB_SERVER=mariadb
      - DB_PORT=3306
      - DB_USER=bwuser
      - DB_PASS=bwuserpass
      - DB_DUMP_FREQUENCY=180
      - DB_DUMP_RETENTION=4w
      - DB_DEBUG=true
      - DB_RUN_ONCE=true
      - DB_DUMP_TARGET=/backup
      - DB_NAMES=bitwarden
    volumes:
      - /var/data/bw-mysql-data-backup:/backup
      - /var/data/scripts/source.sh:/scripts.d/source.sh
      - /var/data/scripts/source.sh:/scripts.d/target.sh
      - /var/data/scripts/pre-backup:/scripts.d/pre-backup
      - /var/data/scripts/post-backup:/scripts.d/post-backup
      - /etc/localtime:/etc/localtime:ro
```

I'm not sure if I'm looking at a file permissions issue here of what?
