### ISSUE TITLE
error creating timer: invalid begin option '320': invalid format for begin delay '320'

### ISSUE THREAD

**Issue by lweberru** [databacker/mysql-backup#409]
hi, I just switched over to current version. I am using a docker-compose to backup my database. But whatever value I enter for DB_DUMP_BEGIN (in my example its 0500), I am getting the error "error creating timer: invalid begin option '320': invalid format for begin delay '320'"
Here is my config
```
  backup:
    image: databack/mysql-backup
    restart: unless-stopped
    user: "0"
    environment:
      - DB_SERVER=db
      - DB_PORT=3306
      - DB_PASS="hidden"
      - DB_NAMES=homeassistant
      - DB_USER=root
      - SINGLE_DATABASE="true"
      - DB_DUMP_FREQ=10080
      - DB_DUMP_BEGIN=0500
      - DB_DUMP_TARGET="/backup"
      - DB_DUMP_SAFECHARS="true"
      - NICE="true"
      - DB_DUMP_RETENTION="3m"
    command: dump
    volumes:
      - ./backup:/backup
```
error log says:

```
mysql-backup-1  | time="2025-02-25T14:57:41Z" level=error msg="error creating timer: invalid begin option '320': invalid format for begin delay '320'"
mysql-backup-1  | time="2025-02-25T14:58:45Z" level=error msg="error creating timer: invalid begin option '320': invalid format for begin delay '320'"
mysql-backup-1  | time="2025-02-25T14:59:58Z" level=error msg="error creating timer: invalid begin option '320': invalid format for begin delay '320'"
mysql-backup-1  | time="2025-02-25T15:01:12Z" level=error msg="error creating timer: invalid begin option '320': invalid format for begin delay '320'"
mysql-backup-1  | time="2025-02-25T15:01:43Z" level=error msg="error creating timer: invalid begin option '320': invalid format for begin delay '320'"
mysql-backup-1  | time="2025-02-25T15:02:03Z" level=error msg="error creating timer: invalid begin option '320': invalid format for begin delay '320'"
mysql-backup-1  | time="2025-02-25T15:02:22Z" level=error msg="error creating timer: invalid begin option '320': invalid format for begin delay '320'"

```
