### ISSUE TITLE
SMB upload not working in v1.0.0 and above

### ISSUE THREAD

**Issue by robweighill** [databacker/mysql-backup#419]
I am having a few issues getting any version from v1.0.0 to upload to an SMB share (Windows hosted).

I receive the following error in the newer versions:
```
time="2025-04-01T11:12:11Z" level=debug msg="starting dump"
time="2025-04-01T11:12:11Z" level=info msg="beginning dump 2025-04-01T11:12:11Z" run=18ed3b36-3223-4d25-b89d-8606feeaa0b6
time="2025-04-01T11:12:19Z" level=debug msg="uploading via protocol smb from db_backup_2025-04-01T11-12-11Z.tgz to db_backup_2025-04-01T11-12-11Z.tgz" run=18ed3b36-3223-4d25-b89d-8606feeaa0b6
Error: error running command: error running command: error running dump: failed to push file: open \db_backup_2025-04-01T11-12-11Z.tgz: leading '\' is not allowed in this operation
time="2025-04-01T11:12:19Z" level=fatal msg="error running command: error running command: error running dump: failed to push file: open \\db_backup_2025-04-01T11-12-11Z.tgz: leading '\\' is not allowed in this operation"
```
If I dump to a local file all works as expected.
I am running in a container, using the following docker compose
 ```
services:
  backup:
    image: databack/mysql-backup
    restart: always
    command: dump
    environment:
     - DB_DUMP_TARGET=smb://<DOMAIN>;<USER>:<PASSWORD>@<SERVER>/DBBackup
     - DB_USER=root
     - DB_PASS=<DBPASS>
     - DB_DUMP_FREQ=360
     - DB_SERVER=mysql
     - DB_NAMES=mydatabase
     - DB_DUMP_RETENTION=28c
     - DB_DEBUG=true
     - DB_DUMP_SAFECHARS=true
```
If I run with `image: databack/mysql-backup:v0.12.0` then the backup works, but the prune doesn't - hence the attempt to update to a new version.

I could be missing something really obvious, so any assistance is very welcomed!

**Comment by robweighill** [comment]
Firstly, thank you for the extremely quick response! Fully appreciate this is all OSS so any help is always appreciated

> 1. Try it with `DBBackup/`? Sure, it should work without the `/`, but let's figure out the boundaries of failure.

No dice here, same errors

> 2. Try it with a subpath? E.g. make a directory inside the share called `test/` (or whatever), and set the target to `smb://<DOMAIN>;<USER>:<PASSWORD>@<SERVER>/DBBackup/test`.

Success! Adding a subpath solved the issue (not sure why I didn't think to try this - apologies).

**Comment by deitch** [comment]
> Success! Adding a subpath solved the issue (not sure why I didn't think to try this - apologies).

This is good. Boundaries defined. Now we can narrow it down and fix it. There is another issue that was fixed recently. relating top pruning. We can get this fixed, and then can cut v1.2.0 with both.

**Comment by deitch** [comment]
@robweighill I just pushed out `databack/mysql-backup: 434e77f83b12ef0749f13a60345d93870b553dfd `. Can you try it and see that your issue is solved, and respond here? Assuming so, that is last I need for cutting a release.

**Comment by robweighill** [comment]
@deitch that's worked perfectly. Thanks again for the speedy fix!

**Comment by deitch** [comment]
Great. v1.2.0 is cut, it should be available on docker hub as `v1.2.0` and `latest` in the next 15 minutes or so, depending on the CI pipeline.

**Comment by robweighill** [comment]
Sorry to resurrect this issue, but we are seeing the same behaviour during prune as well.
I didn't notice this when testing for you before as we did not have any backups which fell into the pruning window. 

Moving backups into /backups solves the issue for now and pruning works. 
I therefore assume you need to add a similar `TrimPrefix` into line 128 in `smb.go` as well as around line 61 in the same file for completeness. (I could be wrong though, Go is not a language I have used!)

**Comment by deitch** [comment]
Pruning is working on file paths target but not SMB target? Can you share your full config again (except secrets, of course) and debug log?

**Comment by robweighill** [comment]
> Pruning is working on file paths target but not SMB target?
Exactly this.
This config produces the error
```
services:
  backup:
    image: databack/mysql-backup
    restart: always
    command: dump
    environment:
     - DB_DUMP_TARGET=smb://<SMBDOMAIN>;<SMBUSER>:<SMBPASS>@<SMBSERVER>/DBBackup
     - DB_USER=root
     - DB_PASS=<DBPASS>
     - DB_DUMP_FREQ=120
     - DB_SERVER=mysql
     - DB_NAMES=mydatabase
     - DB_DUMP_RETENTION=7d
     - DB_DUMP_SAFECHARS=true
```
Error:
```
time="2025-04-04T10:15:07Z" level=fatal msg="error running command: error running command: error running prune: failed to prune target smb://***/DBBackup: failed to remove file db_backup_2025-03-28T14-51-00Z.tgz: remove \\db_backup_2025-03-28T14-51-00Z.tgz: leading '\\' is not allowed in this operation"
Error: error running command: error running command: error running prune: failed to prune target smb://***/DBBackup: failed to remove file db_backup_2025-03-28T14-51-00Z.tgz: remove \db_backup_2025-03-28T14-51-00Z.tgz: leading '\' is not allowed in this operation
```

Like with the saving, if I put everything within a folder in the share it all works, saves, prunes etc.
