### ISSUE TITLE
Restore from s3://path/to/xxx.tgz does not work in docker-compose.yml

### ISSUE THREAD

**Issue by human211** [databacker/mysql-backup#432]
My docker-compose.yml
```
version: "3.9"

services:
  mysql-restore:
    image: databack/mysql-backup:1.2.2
    container_name: mysql-restore
    hostname: mysql-restore
    restart: no
    environment:
      DB_SERVER: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_RESTORE_TARGET: s3://db/db_backup_2025-04-19T19:42:11Z.tgz
      AWS_ACCESS_KEY_ID: ${S3_KEY}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_KEY}
      AWS_ENDPOINT_URL: "https://${S3_HOST}/"
      AWS_DEFAULT_REGION: eu-central1
      COMPRESSION: gzip
      DB_DUMP_DEBUG: "true"
    command: restore
    networks:
      - intranet
networks:
  intranet:
    name: intranet
    external: true
```

I get an error
```
time="2025-04-19T22:21:58Z" level=fatal msg="requires at least 1 arg(s), only received 0"
mysql-restore exited with code 1
```
Аlso my attempts to change
```
DB_RESTORE_TARGET: s3://db/ db_backup_2025-04-19T19:42:11Z.tgz (with space before filename)

DB_RESTORE_TARGET: s3://db/
with one of
command: restore --target=db_backup_2025-04-19T19:42:11Z.tgz
command: restore --target db_backup_2025-04-19T19:42:11Z.tgz
command: restore db_backup_2025-04-19T19:42:11Z.tgz
```
But nothing helps. in the documentation everything is different everywhere. it is not clear how it should be. I also tried to request a docker-compose.yml from the grok but also unsuccessfully

**Comment by shaunakv1** [comment]
want to add plus one to this.  My restore to s3 compliant DigitalOcean Spaces isn't working either. Dump works just fine with the documented config patterns but restore doesn't. 


Here's my backup and restore docker compose 

```yaml
  services:
    mysql-backup:
      image: databack/mysql-backup:master
      environment:
        DB_DEBUG: ${DB_DEBUG}
        DB_SERVER: ${DB_SERVER}
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_DUMP_INCLUDE: ${DB_DUMP_INCLUDE}
        SINGLE_DATABASE: ${SINGLE_DATABASE} 
        NO_DATABASE_NAME: ${NO_DATABASE_NAME}
        DB_DUMP_ONCE: ${DB_DUMP_ONCE}
        DB_DUMP_TRIGGERS_AND_FUNCTIONS: ${DB_DUMP_TRIGGERS_AND_FUNCTIONS}
        DB_DUMP_TARGET: ${DB_DUMP_TARGET}
        DB_DUMP_SAFECHARS: ${DB_DUMP_SAFECHARS}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
        AWS_REGION: ${AWS_REGION}
      command: dump
    mysql-restore:
      image: databack/mysql-backup:master
      environment:
        DB_DEBUG: ${DB_DEBUG}
        RESTORE_DATABASE: ${RESTORE_DATABASE}
        DB_SERVER: ${DB_RESTORE_SERVER}
        DB_PORT: ${DB_RESTORE_PORT}
        DB_USER: ${DB_RESTORE_USER}
        DB_PASS: ${DB_RESTORE_PASS}
        DB_RESTORE_TARGET: ${DB_RESTORE_TARGET}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
        AWS_REGION: ${AWS_REGION}
      command: ["restore", "db_backup_2025-04-26T04-25-56Z.tgz"]
```

relevant env variables
```bash
DB_DUMP_TARGET="s3://rlogx-db-backups/rlogx-prod/"
DB_RESTORE_TARGET="s3://rlogx-db-backups/rlogx-prod"
AWS_ENDPOINT_URL="https://nyc3.digitaloceanspaces.com"
```

### Note rlogx-db-backups in the dump and restore is the bucket name that resolves with subdomain scheme. It works for dump but not for restore


Here's the full error log

```bash
dc up mysql-restore
[+] Running 1/1
 ✔ Container iac-mysql-restore-1  Created                                                                                                              0.0s
Attaching to mysql-restore-1
mysql-restore-1  | time="2025-04-29T03:15:39Z" level=debug msg="starting restore"
mysql-restore-1  | time="2025-04-29T03:15:39Z" level=info msg="beginning restore" run=a731f92f-6258-4203-ad0a-ed9b2a636ec6
mysql-restore-1  | time="2025-04-29T03:15:39Z" level=debug msg="restoring via s3 protocol, temporary file location /tmp/restorefile" run=a731f92f-6258-4203-ad0a-ed9b2a636ec6
mysql-restore-1  | Error: error restoring: failed to pull target &{{s3  %!s(*url.Userinfo=<nil>) rlogx-db-backups /rlogx-prod  %!s(bool=false) %!s(bool=false)   } %!s(bool=false)    }: failed to download file, operation error S3: GetObject, https response error StatusCode: 404, RequestID: tx00000b4758bb0507878d0-006810445b-2b885477-nyc3d, HostID: 2b885477-nyc3d-nyc3-zg04, NoSuchKey:
mysql-restore-1  | time="2025-04-29T03:15:39Z" level=fatal msg="error restoring: failed to pull target &{{s3  %!s(*url.Userinfo=<nil>) rlogx-db-backups /rlogx-prod  %!s(bool=false) %!s(bool=false)   } %!s(bool=false)    }: failed to download file, operation error S3: GetObject, https response error StatusCode: 404, RequestID: tx00000b4758bb0507878d0-006810445b-2b885477-nyc3d, HostID: 2b885477-nyc3d-nyc3-zg04, NoSuchKey: "
mysql-restore-1 exited with code 1
```

Something is wrong with restore and reading of config to generate the correct path.
