### ISSUE TITLE
Feature Request: default location for config file and pre/post scripts

### ISSUE THREAD

**Issue by ZetaMap** [databacker/mysql-backup#442]
It's possible or not to have a feature that search in a default location to get the config and pre/post scripts?
Like that, we can just edit the config in ``/etc/mysql-backup/config.yml``, for example, and run ``mysql-backup dump`` without arguments.

For me, this would be a great feature, as I'm currently creating an Exherbo package of your tool, which I'll then use in an Ansible role to automatically generate and deploy configurations to database VMs. 
This way, with another Ansible role, I could run a backup of all the VMs by simply running "mysql-backup dump --target=s3" and upload them to the S3 target.

**Comment by ZetaMap** [comment]
ok. Also, I noticed that the documentation on the config file format is not very clear. One paragraph says to configure something like this, then another in another file says that it must be done in another way, and the example files show other methods. So I'm a little confused about how to format the file.

Like for scheduling:
**configuration.md** said like that: ```yaml
dump:
  schedule:
    frequency: 60
```
but **scheduling.md** said: ```yaml
dump:
    frequency: 60
```

or for targets, e.g. s3; the **local.yaml** example said: ```yaml
    s3:
      type: s3
      url: s3://bucket.us-west.amazonaws.com/databackup
      details:
        region: us-west-1
        endpoint: https://s3.us-west-1.amazonaws.com
        accessKeyId: access_key_id
        secretAccessKey: secret_access_key
```
but **configuration.md** said to put "spec" instead of "details,
and the **telemetry.yaml** example said: ```yaml
    s3:
      type: s3
      url: s3://bucket.us-west.amazonaws.com/databackup
      region: us-west-1
      endpoint: https://s3.us-west-1.amazonaws.com
      credentials:
        accessKeyId: access_key_id
        secretAccessKey: secret_access_key
```
...
And so on, for many things. 

Idk if the docis old, but it should be updated, because I'm a bit confused.
