### ISSUE TITLE
DB_DUMP_POST_BACKUP_SCRIPTS

### ISSUE THREAD

**Issue by francescotau** [databacker/mysql-backup#448]
The scripts set via the `DB_DUMP_POST_BACKUP_SCRIPTS` variable are executed **before** the backup file is created. Why?

**Comment by deitch** [comment]
Can you create an example showing it?

**Comment by francescotau** [comment]
`compose.yaml`
```
version: "3"

services:
  database:
    image: mysql:8.3
    restart: unless-stopped
    env_file:
      - path: ./.env
    ports:
      - "3306:3306"
    volumes:
      - ./volumes:/var/lib/mysql
    networks:
      - db-net

  backup:
    image: databack/mysql-backup
    restart: unless-stopped
    env_file:
      - path: ./.env
    depends_on:
      - database
    volumes:
      - ./backup:/backup
      - ./post-backup:/scripts.d/post-backup/
    networks:
      - db-net

networks:
  db-net:
    driver: bridge
```

`.env`
```
# database
MYSQL_ROOT_PASSWORD="secret"

# backup
DB_SERVER="database"
DB_PORT="3306"
DB_USER="root"
DB_PASS="secret"
DB_DUMP_FREQ="1"
DB_DUMP_TARGET="/backup"
DB_DUMP_BEGIN="+1"
DB_DUMP_SAFECHARS="true"
```

`post-backup/post-backup.sh`
```
#!/bin/bash

BACKUP_DIR="/backup"

echo "🚀 Post backup script started"

sleep 5 # Trying to sleep in order to wait for the backup file to be created. Not working.

LAST_BACKUP_FILE=$(ls -1 "$BACKUP_DIR" | tail -n 1)
if [ -z "$LAST_BACKUP_FILE" ]; then
  echo "⚠️ No backups found in $BACKUP_DIR"
  exit 1
fi

echo "✅ Last backup file $LAST_BACKUP_FILE"
```
