### ISSUE TITLE
How does the DB_DUMP_RETENTION option work?

### ISSUE THREAD

**Issue by francescotau** [databacker/mysql-backup#449]
Maybe I'm wrong, but I expected that setting `DB_DUMP_RETENTION="2c"` would keep at most two backup files in `/backup`. Instead, a new file is created at each iteration and the previous ones are not deleted. What am I missing? Thanks.

**Comment by deitch** [comment]
Correct, that is what it should do. There was an issue a while back where it was missing it, but it was fixed (cannot recall the PR offhand). If you are having an issue, please:

1. Post your entire config (be careful to remove sensitive data like passwords)
2. Enable debug (`DB_DEBUG=true` or `--debug=true`) and post the messages (again, be careful to remove sensitive data)

**Comment by francescotau** [comment]
`compose.yaml`
```
version: "3"

services:
  database:
    image: mysql:8.3
    restart: unless-stopped
    env_file:
      - path: ./.env
    ports:
      - "3306:3306"
    volumes:
      - ./volumes:/var/lib/mysql
    networks:
      - db-net

  backup:
    image: databack/mysql-backup
    restart: unless-stopped
    env_file:
      - path: ./.env
    depends_on:
      - database
    volumes:
      - ./backup:/backup
    networks:
      - db-net

networks:
  db-net:
    driver: bridge
```
`.env`
```
# database
MYSQL_ROOT_PASSWORD="secret"

# backup
DB_SERVER="database"
DB_PORT="3306"
DB_USER="root"
DB_PASS="secret"
DB_DUMP_FREQ="1"
DB_DUMP_BEGIN="+1"
DB_DUMP_TARGET="/backup"
DB_DUMP_SAFECHARS="true"
DB_DUMP_RETENTION="2c"
```
