### ISSUE TITLE
Crontab with day of week breaks

### ISSUE THREAD

**Issue by carlocaprini** [databacker/mysql-backup#95]
When running the backup with the docker image and a cron configuration with day of week, my container crashes with the following error:

```
/functions.sh: line 304: [: : integer expression expected
/functions.sh: line 307: 8 +  : syntax error: operand expected (error token is "+  ")
```

The docker service configuration I am using looks like this:

```
version: "3.1"

services:
  backup:
    image: databack/mysql-backup
    volumes:
      - ./backups:/db
    env_file:
      - mysql-credentials.env
    environment:
      - DB_DUMP_TARGET=/db
      - DB_DUMP_CRON=0 0 * * 1
      - DB_SERVER=container.network
      - DB_DUMP_BY_SCHEMA=true
    networks:
      - network
``` 

I have tried out different cron configurations and the only ones that brakes are the one for which I don't use `*` as fifth parameter. Am I missing something?
Thank you for the support!
