### ISSUE TITLE
MYSQLDUMP_OPTS doesn't work

### ISSUE THREAD

**Issue by elderapo** [databacker/mysql-backup#99]
I have `docker-compose.yml` file like:

```yml
version: "3"
services:
  ...

  backup:
    image: deitch/mysql-backup
    network_mode: bridge
    restart: always
    volumes:
      - ${BACKUPS_DIR}:/backups
    environment:
      ...
      MYSQLDUMP_OPTS: --routines=true
```

Because I want dump to contain stored procedures but with `MYSQLDUMP_OPTS` set to `--routines=true` I get:
```sh
backup_1             | DB_PORT not provided, defaulting to 3306
backup_1             | Starting at Mon Apr 8 21:34:19 UTC 2019
backup_1             | mysqldump: unknown variable 'OPTS=--routines=true'
```

I've also tried `-R`, `--routines` but nothing seems to work.
